In [30]:
import pandas as pd

In [31]:
new_ref = pd.read_csv('/Users/fionachow/Documents/NYU/CDS/Summer 2024/Human rDNA Research/Project/Human-rDNA/outputs/src_outputs/1000_genome_new_ref/1000_genome_new_ref_v3_reindex_df.csv')

In [35]:
display(new_ref.head(83))

    POS REF
0     1   G
1     2   C
2     3   T
3     4   G
4     5   A
..  ...  ..
78   79   G
79   80   A
80   81   C
81   82   C
82   83   C

[83 rows x 2 columns]

In [37]:
new_ref[new_ref['REF'].str.len() != 1]

Empty DataFrame
Columns: [POS, REF]
Index: []

In [38]:
new_ref

         POS REF
0          1   G
1          2   C
2          3   T
3          4   G
4          5   A
...      ...  ..
13360  13361   T
13361  13362   C
13362  13363   G
13363  13364   C
13364  13365   G

[13365 rows x 2 columns]